"""add specialty to ahpra and mbs items tables

Revision ID: 0258ed0ddb0b
Revises: ec0e930a6516
Create Date: 2026-03-09 21:47:20.788536

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0258ed0ddb0b'
down_revision: str | Sequence[str] | None = 'ec0e930a6516'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbs_items',
    sa.Column('mbs_item_id', sa.String(length=36), nullable=False),
    sa.Column('item_number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('group', sa.String(length=200), nullable=True),
    sa.Column('subgroup', sa.String(length=200), nullable=True),
    sa.Column('schedule_fee', sa.Float(), nullable=True),
    sa.Column('benefit_75', sa.Float(), nullable=True),
    sa.Column('benefit_85', sa.Float(), nullable=True),
    sa.Column('gynaecology_relevance', sa.Text(), nullable=True),
    sa.Column('item_start_date', sa.String(length=20), nullable=True),
    sa.Column('item_end_date', sa.String(length=20), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('mbs_item_id')
    )
    op.create_index(op.f('ix_mbs_items_item_number'), 'mbs_items', ['item_number'], unique=True)
    op.create_table('clinician_mbs_mappings',
    sa.Column('mapping_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('mbs_item_id', sa.String(length=36), nullable=False),
    sa.Column('relevance_basis', sa.Text(), nullable=True),
    sa.Column('link_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['master_clinicians.clinician_id'], ),
    sa.ForeignKeyConstraint(['mbs_item_id'], ['mbs_items.mbs_item_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.add_column('ahpra_registrations', sa.Column('specialty', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ahpra_registrations', 'specialty')
    op.drop_table('clinician_mbs_mappings')
    op.drop_index(op.f('ix_mbs_items_item_number'), table_name='mbs_items')
    op.drop_table('mbs_items')
    # ### end Alembic commands ###
