"""add_clinician_source_links_table

Revision ID: 8f4e197b18cb
Revises: 6e40e0137057
Create Date: 2026-03-11 16:58:44.958893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4e197b18cb'
down_revision: Union[str, Sequence[str], None] = '6e40e0137057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician_source_links',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=False),
    sa.Column('name_raw', sa.String(length=500), nullable=True),
    sa.Column('name_normalised', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['master_clinicians.clinician_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('clinician_id', 'source', 'source_record_id', name='uq_clinician_source_record')
    )
    op.create_index(op.f('ix_clinician_source_links_clinician_id'), 'clinician_source_links', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_clinician_source_links_source_record_id'), 'clinician_source_links', ['source_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinician_source_links_source_record_id'), table_name='clinician_source_links')
    op.drop_index(op.f('ix_clinician_source_links_clinician_id'), table_name='clinician_source_links')
    op.drop_table('clinician_source_links')
    # ### end Alembic commands ###
