"""initial_schema

Revision ID: 941d8f849f05
Revises: 
Create Date: 2026-03-09 14:09:07.540697

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '941d8f849f05'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('name_raw', sa.String(length=500), nullable=False),
    sa.Column('name_normalised', sa.String(length=500), nullable=True),
    sa.Column('affiliation_raw', sa.String(length=1000), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_authors_name_normalised'), 'authors', ['name_normalised'], unique=False)
    op.create_table('college_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name_raw', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('subspecialty', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('committee_roles', sqlite.JSON(), nullable=True),
    sa.Column('speaker_history', sqlite.JSON(), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('grants',
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('nhmrc_id', sa.String(length=50), nullable=True),
    sa.Column('recipient_name_raw', sa.String(length=500), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('keywords', sqlite.JSON(), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_index(op.f('ix_grants_nhmrc_id'), 'grants', ['nhmrc_id'], unique=True)
    op.create_table('institutional_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name_raw', sa.String(length=500), nullable=False),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('research_interests', sa.String(length=2000), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('master_clinicians',
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('name_display', sa.String(length=500), nullable=True),
    sa.Column('name_normalised', sa.String(length=500), nullable=True),
    sa.Column('primary_institution', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('subspecialty', sa.String(length=200), nullable=True),
    sa.Column('source_flags', sqlite.JSON(), nullable=True),
    sa.Column('pub_count', sa.Integer(), nullable=True),
    sa.Column('trial_count', sa.Integer(), nullable=True),
    sa.Column('grant_count', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('h_index_proxy', sa.Integer(), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('early_adopter_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('degree_centrality', sa.Float(), nullable=True),
    sa.Column('betweenness_centrality', sa.Float(), nullable=True),
    sa.Column('clustering_coefficient', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('clinician_id')
    )
    op.create_index(op.f('ix_master_clinicians_name_normalised'), 'master_clinicians', ['name_normalised'], unique=False)
    op.create_table('papers',
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('pmid', sa.String(length=20), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=2000), nullable=True),
    sa.Column('pub_date', sa.String(length=20), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_pmid'), 'papers', ['pmid'], unique=True)
    op.create_table('trials',
    sa.Column('trial_id', sa.String(length=36), nullable=False),
    sa.Column('anzctr_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=2000), nullable=True),
    sa.Column('pi_name_raw', sa.String(length=500), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('conditions', sqlite.JSON(), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('trial_id')
    )
    op.create_index(op.f('ix_trials_anzctr_id'), 'trials', ['anzctr_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=True),
    sa.Column('field_changed', sa.String(length=200), nullable=True),
    sa.Column('old_value', sa.String(length=2000), nullable=True),
    sa.Column('new_value', sa.String(length=2000), nullable=True),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['master_clinicians.clinician_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('clinician_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('profile_summary', sa.String(length=5000), nullable=True),
    sa.Column('engagement_approach', sa.String(length=5000), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['master_clinicians.clinician_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('clinician_id')
    )
    op.create_table('coauthorships',
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('author_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('author_id', 'paper_id')
    )
    op.create_table('review_signals',
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('place_id', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('keyword_mentions', sqlite.JSON(), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['master_clinicians.clinician_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_signals')
    op.drop_table('coauthorships')
    op.drop_table('clinician_profiles')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_trials_anzctr_id'), table_name='trials')
    op.drop_table('trials')
    op.drop_index(op.f('ix_papers_pmid'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_master_clinicians_name_normalised'), table_name='master_clinicians')
    op.drop_table('master_clinicians')
    op.drop_table('institutional_profiles')
    op.drop_index(op.f('ix_grants_nhmrc_id'), table_name='grants')
    op.drop_table('grants')
    op.drop_table('college_profiles')
    op.drop_index(op.f('ix_authors_name_normalised'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
