"""add_canrefer_ahpra_verification_tables

Revision ID: dda5a8653594
Revises: 941d8f849f05
Create Date: 2026-03-09 17:28:31.718069

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'dda5a8653594'
down_revision: str | Sequence[str] | None = '941d8f849f05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ahpra_registrations',
    sa.Column('registration_id', sa.String(length=36), nullable=False),
    sa.Column('name_raw', sa.String(length=500), nullable=False),
    sa.Column('name_normalised', sa.String(length=500), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('registration_type', sa.String(length=100), nullable=True),
    sa.Column('registration_status', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('search_profession', sa.String(length=200), nullable=True),
    sa.Column('search_state', sa.String(length=50), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_index(op.f('ix_ahpra_registrations_name_normalised'), 'ahpra_registrations', ['name_normalised'], unique=False)
    op.create_index(op.f('ix_ahpra_registrations_registration_number'), 'ahpra_registrations', ['registration_number'], unique=True)
    op.create_index(op.f('ix_ahpra_registrations_state'), 'ahpra_registrations', ['state'], unique=False)
    op.create_table('canrefer_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name_raw', sa.String(length=500), nullable=False),
    sa.Column('name_normalised', sa.String(length=500), nullable=True),
    sa.Column('given_name', sa.String(length=200), nullable=True),
    sa.Column('family_name', sa.String(length=200), nullable=True),
    sa.Column('honorific_prefix', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('job_titles', sqlite.JSON(), nullable=True),
    sa.Column('languages', sqlite.JSON(), nullable=True),
    sa.Column('work_locations', sqlite.JSON(), nullable=True),
    sa.Column('hospitals', sqlite.JSON(), nullable=True),
    sa.Column('mdts', sqlite.JSON(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_canrefer_profiles_name_normalised'), 'canrefer_profiles', ['name_normalised'], unique=False)
    op.create_index(op.f('ix_canrefer_profiles_slug'), 'canrefer_profiles', ['slug'], unique=True)
    op.create_index(op.f('ix_canrefer_profiles_state'), 'canrefer_profiles', ['state'], unique=False)
    op.create_table('registration_verifications',
    sa.Column('verification_id', sa.String(length=36), nullable=False),
    sa.Column('canrefer_profile_id', sa.String(length=36), nullable=True),
    sa.Column('ahpra_registration_id', sa.String(length=36), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ahpra_registration_id'], ['ahpra_registrations.registration_id'], ),
    sa.ForeignKeyConstraint(['canrefer_profile_id'], ['canrefer_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_verifications')
    op.drop_index(op.f('ix_canrefer_profiles_state'), table_name='canrefer_profiles')
    op.drop_index(op.f('ix_canrefer_profiles_slug'), table_name='canrefer_profiles')
    op.drop_index(op.f('ix_canrefer_profiles_name_normalised'), table_name='canrefer_profiles')
    op.drop_table('canrefer_profiles')
    op.drop_index(op.f('ix_ahpra_registrations_state'), table_name='ahpra_registrations')
    op.drop_index(op.f('ix_ahpra_registrations_registration_number'), table_name='ahpra_registrations')
    op.drop_index(op.f('ix_ahpra_registrations_name_normalised'), table_name='ahpra_registrations')
    op.drop_table('ahpra_registrations')
    # ### end Alembic commands ###
