"""add nct_id to trials

Revision ID: ec0e930a6516
Revises: dda5a8653594
Create Date: 2026-03-09 19:58:48.455327

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ec0e930a6516'
down_revision: str | Sequence[str] | None = 'dda5a8653594'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('nct_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_trials_nct_id'), 'trials', ['nct_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trials_nct_id'), table_name='trials')
    op.drop_column('trials', 'nct_id')
    # ### end Alembic commands ###
